---
like:
  position: 1
  name: Like
  icon: sparkle-heart
thumbsup:
  position: 2
  score: 5.0
  icon: thumb-up
thumbsdown:
  position: 3
  score: -10.0
  icon: thumb-down
unicorn:
  position: 4
  name: Unicorn
  icon: multi-unicorn
exploding_head:
  position: 5
  icon: exploding-head
raised_hands:
  position: 6
  icon: raised-hands
fire:
  position: 7
  icon: fire
readinglist:
  position: 7
  icon: save
  published: false
vomit:
  privileged: true
  name: Vomit
  score: -50.0
thinking:
  published: false
hands:
  published: false
